administrator/urls.py
from django.urls import path
from . import views

app_name = 'administrator'

urlpatterns = [
    path('', views.DashBoard.as_view(), name='dash'),

    path('institution/<int:pk>/details/', views.InstitutionDetail.as_view(), name='institution_details'),
    path('institution/add_grading_list/', views.AddGradingValues.as_view(), name='add_grading_list'),

    path('course/<int:pk>/update/', views.CourseUpdate.as_view(), name='course_update'),
    path('course/<int:program_pk>/add/', views.CourseCreate.as_view(), name='add_course'),  # single course
    path('courses/<int:program_pk>/add/', views.CoursesCreateView.as_view(), name='add_courses'),  # Multiple courses


    path('program/add/', views.AddProgram.as_view(), name='create_program'),
    path('program/<int:pk>/delete/', views.DeleteProgram.as_view(), name='delete_program'),
    path('program/<int:pk>/update/', views.ProgramUpdate.as_view(), name='update_program'),

    path('lecturers/', views.Lecturers.as_view(), name='lecturers'),
    path('lecturers/<int:pk>/update/', views.LecturerUpdate.as_view(), name="lecturer_details"),
    path('lecturers/add/', views.Lecturers.as_view(), name='lecturers'),

    path('students/', views.Students.as_view(), name='students'),
    path('students/<int:pk>/details', views.StudentDetails.as_view(), name='student_details'),
    path('students/add/', views.StudentsAdd.as_view(), name='add_students'),

    path('exams/', views.ExamsView.as_view(), name='exams'),
    path('exams/<int:pk>/details', views.ExamsDetail.as_view(), name='exam_details'),  # filter ExamRegister
    path('exams/<int:pk>/update/', views.ExamsUpdate.as_view(), name='update_exam'),  # You Know The drill
    path('exams/add/', views.ExamsAdd.as_view(), name='add_exam'),
    path('exams/publish/', views.PublishExam.as_view(), name='publish_exam'),

    path('notifications/', views.Notifications.as_view(), name='notifications'),
    path('notifications/add/', views.NotificationAdd.as_view(), name='add_notification'),
    path('notification/<int:pk>/delete/', views.NotificationDeleteView.as_view(), name='news_delete'),

    path('accounts/', views.Accounts.as_view(), name='accounts'),
    path('accounts/invoices/', views.InvoiceList.as_view(), name='invoice_list'),
    path('accounts/invoices/<int:pk>/delete', views.InvoiceDelete.as_view(), name='invoice_delete'),
    path('accounts/invoice/<int:pk>/update', views.InvoiceUpdate.as_view(), name='invoice_update'),
    path('accounts/invoice/filter/add/', views.InvoiceStudentsFilter.as_view(), name='invoice_students_filter'),
    path('accounts/invoice/add/<int:program_pk>/<int:year>/<int:semester>/<int:extra>/',
         views.CreateInvoices.as_view(), name='add_invoice'),

    path('accounts/payments/', views.PaymentList.as_view(), name='payment_list'),
    path('accounts/payments/add/', views.RecordPayments.as_view(), name='add_payment'),
    path('accounts/payments/<int:pk>/', views.PaymentDetails.as_view(), name='payment_details'),


]

headway/urls.py
from django.urls import path
from . import views

app_name = 'headway'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('student/', views.StudentHome.as_view(), name='student_home'),
    path('lecturer/', views.LecturerHome.as_view(), name='lecturer_home'),
    path('result/list/', views.ResultList.as_view(), name='result_list'),
    path('icons/', views.Icons.as_view(), name='icons'),
    path('notifications/', views.Notifications.as_view(), name='notifications'),
    path('user/', views.UserView.as_view(), name='user'),

    path('course/register/', views.CourseRegistration.as_view(), name='course_registration'),
    path('course/register/lecturer/', views.LecturerCourseRegistration.as_view(), name='lecturer_course_registration'),

    path('courses/', views.Courses.as_view(), name='courses'),
    path('course/<int:pk>/details/', views.CourseDetails.as_view(), name='course_detail'),
    path('course/cleared/', views.CompletedCourses.as_view(), name='completed_courses'),
    path('course/<int:pk>/grade/', views.GradeCourseView.as_view(), name='grade_course'),

    path('file/upload/<int:course_id>/', views.UploadFiles.as_view(), name='upload_file'),
    path('file/<int:pk>/delete/<int:course_id>/', views.FileDeleteView.as_view(), name='delete_file'),
    path('published/papers/upload', views.PaperAdd.as_view(), name='paper_upload'),
    path('published/papers/', views.PapersView.as_view(), name='papers'),
    path('published/paper/<int:pk>/delete/', views.PaperDeleteView.as_view(), name='paper_delete'),

    path('videos/<int:playlist_pk>/playlist/', views.VideoSeriesView.as_view(), name='video_play_list'),
    path('videos/upload/<int:course_id>/', views.VideoUpload.as_view(), name='upload_video'),
    path('videos/<int:pk>/delete/<int:course_id>/', views.VideoDelete.as_view(), name='video_delete'),

    path('notifications/add/', views.NotificationAdd.as_view(), name='add_notification'),
    path('notification/<int:pk>/delete/', views.NotificationDeleteView.as_view(), name='news_delete'),
    path('notification/<int:pk>/details/', views.NotificationDetail.as_view(), name='notification_details'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('accounts/', views.Accounts.as_view(), name='student_accounts'),
]

administrator/models.py
from django.db import models
from headway.models import Student, Institution, User
from django.urls import reverse


# ----------------- Accounts Models ---------
class Charges(models.Model):
    invoice = models.ForeignKey('Invoice', on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    amount = models.FloatField()


class Invoice(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    description = models.CharField(max_length=250, null=True)
    total_amount = models.FloatField(null=True, blank=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, blank=True)
    prepared_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_created=True, auto_now_add=True)

    def __str__(self):
        return str(self.student.program) + 'Year: ' + str(self.student.year)\
               + ' Semester: ' + str(self.student.semester) + ' : ' + str(self.date.date())


class Payments(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    paid_to = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField()
    description = models.CharField(max_length=200)
    receipt_no = models.CharField(max_length=120)
    date = models.DateTimeField(auto_created=True, auto_now=True)

    def get_absolute_url(self):
        return reverse('administrator:payment_details', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.student) + ' ' + str(self.description)

administrator/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, UpdateView, CreateView, DetailView, DeleteView, ListView, FormView
from django.db import transaction

from headway.models import Program, News, Course, Exam, Lecturer, Student, ExamRegister, Institution, User, GradingList
from administrator.models import Invoice, Charges, Payments
from django.db.models import Q
from django.utils.decorators import method_decorator
from .import forms
# from headway.mixins import RequestFormKwargsMixin
from Sentinel.decorators import user_is_admin
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
import datetime


@method_decorator(user_is_admin, name='get')
class InstitutionDetail(DetailView):
    template_name = 'administrator/institute_details.html'
    model = Institution


@method_decorator(user_is_admin, name='get')
class DashBoard(TemplateView):  # add pagination
    template_name = 'administrator/dashboard.html'

    def get(self, request, *args, **kwargs):
        programs = Program.objects.filter(institution=self.request.user.institution).order_by('id')
        paginator = Paginator(programs, 10)
        page = request.GET.get('page')
        programs = paginator.get_page(page)

        context = {'programs': programs, }
        return render(request, self.template_name, context)


# #####################Lecturers#############
@method_decorator(user_is_admin, name='get')
class Lecturers(TemplateView):
        template_name = 'administrator/lecturers.html'

        def get(self, request, *args, **kwargs):
            # get a Lecturers/ access user
            lecturers = Lecturer.objects.filter(user__institution=self.request.user.institution)

            context = {
                'lecturers': lecturers,
                       }
            return render(request, self.template_name, context)


@method_decorator(user_is_admin, name='get')
@method_decorator(user_is_admin, name='post')
class LecturerUpdate(FormView):
    template_name = 'administrator/lecturer_details.html'

    def get(self, request, *args, **kwargs):
        lecturer = Lecturer.objects.get(pk=self.kwargs['pk'])
        user_form = forms.UserForm(instance=lecturer.user)
        lecturer_form = forms.LecturerForm(instance=lecturer)

        context = {'user_form': user_form,
                   'lecturer_form': lecturer_form, }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        lecturer = Lecturer.objects.get(pk=self.kwargs['pk'])
        user_form = forms.UserForm(request.POST, instance=lecturer.user)
        lecturer_form = forms.LecturerForm(request.POST, instance=lecturer)

        if user_form.is_valid() and lecturer_form.is_valid():
            user_form.save()
            lecturer_form.save()
            messages.success(request, "Lecturer Information updated")
            return redirect('administrator:lecturers')


# #####################Students#############
@method_decorator(user_is_admin, name='get')
@method_decorator(user_is_admin, name='post')
class Students(FormView):
    template_name = 'administrator/students.html'

    def get(self, request, *args, **kwargs):
        filter_form = forms.StudentFilterForm()
        program_list = Program.objects.filter(institution=self.request.user.institution)

        context = {
                'program_list': program_list,
                'filter_form': filter_form,
            }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        filter_form = forms.StudentFilterForm(request.POST)
        students = None
        program = None
        year = None
        semester = None
        if filter_form.is_valid():
            program_pk = self.request.POST.get('program_pk')
            year = filter_form.cleaned_data['year']
            semester = filter_form.cleaned_data['semester']

            program = Program.objects.get(pk=program_pk)

            students = Student.objects.filter(Q(program=program) &
                                              Q(year=year) &
                                              Q(semester=semester) &
                                              Q(is_active=True))
        context = {
            'students': students,
            'program': program,
            'first_student': students.first(),
            'year': year,
            'semester': semester,
        }
        return render(request, self.template_name, context)


@method_decorator(user_is_admin, name='get')
class StudentDetails(DetailView):
    template_name = 'administrator/student_detail.html'
    model = Student
    context_object_name = 'student'


# adding multiple students
@method_decorator(user_is_admin, name='get')
@method_decorator(user_is_admin, name='post')
class StudentsAdd(FormView):
    template_name = 'administrator/students_add.html'

    def get(self, request, *args, **kwargs):
        program_pk = self.request.GET.get('program_pk')
        year = self.request.GET.get('student_year')
        semester = self.request.GET.get('student_semester')
        # queries
        program = Program.objects.get(pk=program_pk)
        queryset = User.objects.filter(Q(institution=self.request.user.institution) &
                                       Q(student__program=program) &
                                       Q(student__year=year) &
                                       Q(student__semester=semester))
        formset = forms.StudentSignUpFormSet(queryset=queryset)
        context = {'formset': formset,
                   'program': program,
                   'year': year,
                   'semester': semester, }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        program_pk = self.request.POST.get('program_pk')
        year = self.request.POST.get('student_year')
        semester = self.request.POST.get('student_semester')
        # queries
        program = Program.objects.get(pk=program_pk)
        queryset = User.objects.filter(Q(institution=self.request.user.institution) &
                                       Q(student__program=program) &
                                       Q(student__year=year) &
                                       Q(student__semester=semester))

        formset = forms.StudentSignUpFormSet(request.POST, queryset=queryset)

        if formset.is_valid():
            instances = formset.save(commit=False)
            for instance in instances:
                with transaction.atomic():
                    # get info from non-committed instance
                    print(instance.username)
                    username = instance.username
                    institution = self.request.user.institution
                    email = str(username) + '@' + str(institution.short_name) + '.com'
                    password = 'password1234'

                    # use data to create user
                    user = User.objects.create_user(username, email, password)
                    # update Extra User fields
                    user.first_name, user.middle_name, user.last_name = \
                        instance.first_name, instance.middle_name, instance.last_name
                    user.institution = institution
                    user.save()
                    Student.objects.create(user=user, year=year, semester=semester, program=program)
                    messages.success(request, 'The Students Were Added Successfully.')

            if not instances:
                messages.info(request, 'No Changes Made.')

        else:
            messages.warning(request, 'Something Went Wrong, We Could Not Validate The User Data.')
            messages.error(request, formset.errors)

        # students for display on redirect to students list.
        students = Student.objects.filter(Q(program=program) &
                                          Q(year=year) &
                                          Q(semester=semester))

        context = {
            'students': students,
            'program': program,
            'first_student': students.first(),
            'year': year,
            'semester': semester,
        }

        return render(request, 'administrator/students.html', context)


# #####################ExamsViews#############
@method_decorator(user_is_admin, name='get')
class ExamsView(ListView):
    template_name = 'administrator/exams.html'
    model = Exam
    ordering = 'start_date'
    context_object_name = 'exams'
    paginate_by = '10'


@method_decorator(user_is_admin, name='post')
@method_decorator(user_is_admin, name='get')
class ExamsAdd(SuccessMessageMixin, CreateView):
    model = Exam
    form_class = forms.ExamForm
    template_name = 'administrator/exams_form.html'
    success_message = "%(name)s Exam was Created Successfully"
    success_url = reverse_lazy('administrator:exams')

    def form_valid(self, form):
        exam = form.save(commit=False)
        exam.institution = self.request.user.institution
        exam.created_by = self.request.user
        super(ExamsAdd, self).form_valid(form)


@method_decorator(user_is_admin, name='get')
@method_decorator(user_is_admin, name='post')
class ExamsUpdate(SuccessMessageMixin, UpdateView):
    template_name = 'administrator/exams_update_form.html'
    model = Exam
    form_class = forms.ExamForm
    success_url = reverse_lazy('administrator:exams')
    success_message = "%(name)s Was Updated Successfully"


@method_decorator(user_is_admin, name='get')
class ExamsDetail(TemplateView):
    template_name = 'administrator/exam_details.html'

    def get(self, request, *args, **kwargs):  # get number of students and number of courses
        exam = Exam.objects.get(pk=self.kwargs['pk'])
        register = ExamRegister.objects.filter(exam=exam)

templates/administrator/add_notification.html
{% extends 'administrator/base.html' %}
{% block title %}Add Notification{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Allowing lectures to add notifications -->
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Add Notifications</h5>
                <p class="card-category">Fill Out The Form Below To Create A Notification</p>
              </div>
              <div class="card-body ">
                    {% if request.user.is_admin %}
                        <form action="" class="form-control" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div id="div_id_title" class="form-group">
                                <label for="id_title" class=" requiredField">
                                    Title
                                    <span class="asteriskField">*</span>
                                </label>
                                <div class="">
                                    <input type="text" name="title" maxlength="200" class="textinput textInput form-control" required id="id_title">
                                </div>
                            </div>
                            <div id="div_id_content" class="form-group">
                                <label for="id_content" class=" requiredField">
                                            Content
                                    <span class="asteriskField">*</span>
                                </label>
                                <div class="">
                                <textarea name="content" cols="40" rows="10" class="textarea form-control" required id="id_content">
                                </textarea>
                                <small id="hint_id_content" class="form-text text-muted">Enter Message Content here.</small>
                            </div>
                            </div>
                            <div class="form-group">
                                <div id="div_id_staff_only" class="">
                                    <input type="checkbox" name="staff_only" class="" id="id_staff_only">
                                    <label for="id_staff_only" class="form-check-label">
                                                Staff only
                                            </label>
                                    <small id="hint_id_staff_only" class="form-text text-muted">Who should See This Message.</small>
                                </div> </div>
                            <input class="btn btn-outline-success" type="submit" value="Send">
                        </form>


                  {% endif %}
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

templates/administrator/exam_details.html
{% extends 'administrator/base.html' %}
{% block title %}Exam Details{% endblock %}

{% block content %}
        <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">{{ exam }}</h5>
                <p class="card-category">Exam Details</p>
              </div>

            {% include 'partials/messages.html' %}

                <div class="card-body">
                    <div class="typography-line"><strong>
                        Students Registered: {{ student_nun }}</strong>
                    </div>
                    <div class="typography-line"><strong>
                        Courses Registered: {{ course_nun }}</strong>
                    </div>
                    <div class="typography-line"><strong>
                        Courses Graded: {{ course_graded_nun }}</strong>
                    </div>
                <br>
                <div class="typography-line">
                    <p>ONLY PUBLISH RESULTS WHEN THE NUMBER ON REGISTERED COURSES IS
                        THE SAME AS THE NUMBER OF GRADED COURSES</p>
                </div>
                <hr class="btn-outline-success">
                    {% if exam.active %}
                        <form action="{% url 'administrator:publish_exam' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="{{ exam.pk }}" name="exam_id">
                            <input type="submit" value="Publish Results" class="btn btn-outline-success btn-sm" >
                        </form>
                    {% else %}
                        <div class="text-info text-center">
                            <h5>Results Published</h5>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

{% endblock content %}

templates/administrator/exams_form.html
{% extends 'administrator/base.html' %}
{% block title %}Add Exam{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Add Exam</h5>
                <p class="card-category">Fill In The Following Form To create An Exam</p>
              </div>
                <div class="card-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" class="btn btn-outline-success" value="Create">
                    </form>
                </div>
            </div>
          </div>
{% endblock content %}

templates/administrator/invoice_student_filter.html
{% extends 'administrator/base.html' %}
{% block title %}Invoice Students Filter{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
        <div class="card ">
          <div class="card-header ">
            <h5 class="card-title ">Student List Filter</h5>
            <p class="card-category">Use The Filters Below To Get A Desired Student List Of The Students You Want To Create An Invoice For.</p>
          </div>
        </div>
    </div>

    {% include 'partials/messages.html' %}

    {% if program_list %}
    {% for program in program_list %}
    <div class="col-md-12">
        <div class="card ">
          <div class="card-header ">
            <h5 class="card-title">{{ forloop.counter }}. {{ program }}</h5>
            <p class="card-category">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ filter_form|crispy }}
                  <input type="hidden" value="{{ program.pk }}" name="program_pk">
                  <input value="Create Student Invoices" type="submit" class="btn-sm btn-outline-info">
                </form>
            </p>
          </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
        <div class="col-md-12">
        <div class="card ">
               <div class="card-header text-center">
                 <h5 class="card-title">No Programs</h5>
                 <p class="card-category">No Programs From Your Institution Have Been Added Yet.</p>
                 <p class="card-category"><strong>Add Programs Before You Can Create Student Invoices.</strong></p>
             <a href="{% url 'administrator:accounts' %}" class="btn btn-primary btn-sm">Ok</a>
             </div>
        </div>
        </div>
    {% endif %}

{% endblock content %}

templates/administrator/invoice_update.html
{% extends 'administrator/base.html' %}
{% block title %}Invoice Update{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
          <div class="col-lg-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Invoice Update</h5>
                <p class="card-category">Fill Form Bellow To Invoice Update The Invoice.</p>
              </div>

                <div class="card-body">
                    {% include 'partials/messages.html' %}
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Update" class="btn btn-outline-success">
                    </form>
                </div>
            </div>
          </div>
        </div>
{% endblock content %}

templates/administrator/make_payment.html
{% extends 'administrator/base.html' %}
{% block title %}Record Payment{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
          <div class="col-lg-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Record Payment</h5>
                <p class="card-category">Fill Form Bellow To Record A Payment.</p>
              </div>

                <div class="card-body">
                    {% include 'partials/messages.html' %}
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Record" class="btn btn-outline-success">
                    </form>
                </div>
            </div>
          </div>
        </div>
{% endblock content %}

templates/administrator/news_confirm_delete.html
{% extends 'administrator/base.html' %}
{% block title %}Delete Confirm {% endblock %}

{% block content %}
    <div class="col-md-12">
            <div class="card text-center">
              <div class="card-header ">
                <h5 class="card-title">Confirm Notification Deletion</h5>
              </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <p> Are you sure you want to delete "{{ object }}"?</p>
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
          </div>
{% endblock content %}

templates/administrator/payment_details.html
{% extends 'administrator/base.html' %}
{% block title %}Record Payment{% endblock %}

{% block content %}
    <div class="row">
          <div class="col-lg-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Payment Details</h5>
                <p class="card-category">Details Of This Payment.</p>
              </div>

                <div class="card-body">
                    {% include 'partials/messages.html' %}
                        <div class="table-responsive">
                          <table class="table">
                            <thead class=" text-primary">
                            </thead>
                            <tbody>
                              <tr>
                                <td>
                                  Student: {{ payment.student }}
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  Paid To: {{ payment.paid_to }}
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  Amount: {{ payment.amount}}
                                </td>
                              </tr>
                              <tr>
                                  <td>
                                  Description: {{ payment.description}}
                                </td>
                              </tr>
                              <tr>
                                  <td>
                                  Receipt No.: {{ payment.receipt_no}}
                                </td>
                              </tr>
                              <tr>
                                  <td>
                                  Date: {{ payment.date}}
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>

                </div>
            </div>
          </div>
        </div>

{% endblock content %}

templates/administrator/program_add.html
{% extends 'administrator/base.html' %}
{% block title %}Add Program{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
          <div class="col-lg-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Create Program</h5>
                <p class="card-category">Fill Form Bellow To Create A Program.</p>
              </div>

                <div class="card-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Create" class="btn btn-outline-success">
                    </form>
                </div>
            </div>
          </div>
        </div>
{% endblock content %}

templates/administrator/program_update.html
{% extends 'administrator/base.html' %}
{% block title %} Program Update{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
          <div class="col-lg-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Update Program</h5>
                <p class="card-category">Fill Form Bellow To Update {{ program }}.</p>
              </div>

                <div class="card-body">
                    <form method="post" action=".">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Update" class="btn btn-outline-success">
                    </form>
                </div>
            </div>
          </div>
        </div>
{% endblock content %}