headway/urls.py
from django.urls import path
from . import views

app_name = 'headway'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('student/', views.StudentHome.as_view(), name='student_home'),
    path('lecturer/', views.LecturerHome.as_view(), name='lecturer_home'),
    path('result/list/', views.ResultList.as_view(), name='result_list'),
    path('icons/', views.Icons.as_view(), name='icons'),
    path('notifications/', views.Notifications.as_view(), name='notifications'),
    path('user/', views.UserView.as_view(), name='user'),

    path('course/register/', views.CourseRegistration.as_view(), name='course_registration'),
    path('course/register/lecturer/', views.LecturerCourseRegistration.as_view(), name='lecturer_course_registration'),

    path('courses/', views.Courses.as_view(), name='courses'),
    path('course/<int:pk>/details/', views.CourseDetails.as_view(), name='course_detail'),
    path('course/cleared/', views.CompletedCourses.as_view(), name='completed_courses'),
    path('course/<int:pk>/grade/', views.GradeCourseView.as_view(), name='grade_course'),

    path('file/upload/<int:course_id>/', views.UploadFiles.as_view(), name='upload_file'),
    path('file/<int:pk>/delete/<int:course_id>/', views.FileDeleteView.as_view(), name='delete_file'),
    path('published/papers/upload', views.PaperAdd.as_view(), name='paper_upload'),
    path('published/papers/', views.PapersView.as_view(), name='papers'),
    path('published/paper/<int:pk>/delete/', views.PaperDeleteView.as_view(), name='paper_delete'),

    path('videos/<int:playlist_pk>/playlist/', views.VideoSeriesView.as_view(), name='video_play_list'),
    path('videos/upload/<int:course_id>/', views.VideoUpload.as_view(), name='upload_video'),
    path('videos/<int:pk>/delete/<int:course_id>/', views.VideoDelete.as_view(), name='video_delete'),

    path('notifications/add/', views.NotificationAdd.as_view(), name='add_notification'),
    path('notification/<int:pk>/delete/', views.NotificationDeleteView.as_view(), name='news_delete'),
    path('notification/<int:pk>/details/', views.NotificationDetail.as_view(), name='notification_details'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('accounts/', views.Accounts.as_view(), name='student_accounts'),
]

headway/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from datetime import timedelta
# signal imports
from django.dispatch import receiver
import os

# CONSTANTS
STATUS = (
    (0, 'In progress'),
    (1, 'Approved'),
    (2, 'Rejected'),
)

DAYS = (
    [(i, i) for i in range(1, 31)]
)

MONTHS = (
    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December'),
)


YEARS = (
        (1, 'First Year'),
        (2, 'Second Year'),
        (3, 'Third Year'),
        (4, 'Fourth Year'),
    )

SEMESTER = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
)

LEVELS = (
    ('Certificate', 'Certificate'),
    ('Diploma', 'Diploma'),
    ('Bachelor', 'Bachelor'),
    ('Masters', 'Masters'),
)

TYPES = (
    ('M', 'Mandatory'),
    ('E', 'Elective'),
)

MARRIED = (
        ('M', 'Married'),
        ('U', 'Unmarried'),
    )

RELATION = (
    ('gma', 'Grand Mother'),
    ('gda', 'Grand Father'),
    ('dad', 'Father'),
    ('mom', 'Mother'),
    ('sis', 'Sister'),
    ('bro', 'Brother'),
    ('unc', 'Uncle'),
    ('aun', 'Auntie'),
    ('cuz', 'Cousin'),
    ('son', 'Son'),
    ('dot', 'Daughter'),)

GRADES = (
    ('A+', 'A+'),
    ('A', 'A'),
    ('B+', 'B+'),
    ('B', 'B'),
    ('C+', 'C+'),
    ('C', 'C'),
    ('D', 'D'),
    )

# THEME_COLORS = (
#    ('White', 'White'),
#    ('Blue', 'Blue'),
#    ('Green', 'Green'),
#    ('Orange', 'Orange'),
#   ('Yellow', 'Yellow'),
#    ('Red', 'Red'),
# )


# CLASSES
# ----------Institution Classes----------
class Institution(models.Model):
    name = models.CharField(max_length=100, help_text='Enter Institution Name')
    active_subscription = models.BooleanField(default=True)
    subscription_type = models.CharField(max_length=1)  # add choices
    subscription_start = models.DateField(auto_created=True, auto_now_add=True)
    subscription_end = models.DateField()
    short_name = models.CharField(max_length=10, default='INSTITUTE', help_text='Enter A Short Abbreviation Of'
                                                                                'Your Institutes Name '
                                                                                '(10 Characters Max.)')
    # theme_color = models.CharField(max_length=6, choices=THEME_COLORS, default=THEME_COLORS[0])

    def __str__(self):
        return self.name + ' ' + str(self.subscription_type)


class GradingList(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    grade = models.CharField(max_length=2, choices=GRADES)
    upper = models.FloatField()
    lower = models.FloatField()

    def __str__(self):
        return  str(self.grade) + ': ' +str(self.upper) + ' TO ' + str(self.lower)


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Enter a Student ID for student Accounts or Email for lecturer Accounts.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_('email address'), blank=True, unique=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    is_student = models.BooleanField(default=True)
    is_lecturer = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE, null=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        if self.middle_name:
            full_name = '%s %s %s' % (self.first_name, self.middle_name, self.last_name)
        else:
            full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name

    def __str__(self):
        return self.get_full_name()


class PersonalDetails(models.Model):
    province = models.CharField(max_length=100, blank=True, null=True)
    district = models.CharField(max_length=100, blank=True, null=True)
    town = models.CharField(max_length=100, blank=True, null=True)
    home_address = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    birthday = models.DateField(verbose_name='Date of Birth', blank=True, null=True)
    marital_status = models.CharField(max_length=1, choices=MARRIED, blank=True, null=True)
    nrc_number = models.CharField(max_length=15, blank=True, null=True)

    class Meta:
        abstract = True


class Guardian(PersonalDetails):
    relation = models.CharField(max_length=3, choices=RELATION)


class Program(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=150)
    summary = models.TextField(null=True, blank=True)
    level = models.CharField(max_length=11, choices=LEVELS, help_text='Qualification Level For The Program.')

    def __str__(self):
        return str(self.name) + ' (' + str(self.level) + ')'

    def get_absolute_url(self):
        return reverse('headway:program_details', kwargs={'pk': self.pk})


class Course(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20, default='CODE_default', help_text='Enter Course Code')
    summary = models.TextField(max_length=600, null=True, blank=True)
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    credits = models.IntegerField(null=True, default=0)
    mandatory = models.BooleanField(default=True)
    year = models.IntegerField(choices=YEARS, default=1)
    semester = models.IntegerField(choices=SEMESTER, default=1)
    course_lecturer = models.ManyToManyField('Lecturer', related_name='course_teacher', blank=True)

    def __str__(self):
        return self.name

    def get_type(self):
        if self.mandatory:
            return "Mandatory"
        else:
            return "Elective"

    def get_absolute_url(self):
        return reverse('headway:course_detail', kwargs={'pk': self.pk})


class CourseRegister(models.Model):
    student = models.ForeignKey('Student', related_name='register', on_delete=models.CASCADE)
    course = models.ForeignKey(Course, related_name='registered_course', on_delete=models.CASCADE)
    date_registered = models.DateTimeField(auto_now_add=True, auto_created=True)
    cleared = models.BooleanField(default=False)


class Student(PersonalDetails):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(null=True, blank=True, default='no-img.png')
    program = models.ForeignKey(Program, on_delete=models.SET_NULL, null=True)
    guardian = models.OneToOneField(Guardian, on_delete=models.SET_NULL, null=True, blank=True)
    courses = models.ManyToManyField(Course, related_name='courses', blank=True, through=CourseRegister)
    year = models.IntegerField(choices=YEARS, default=1)
    semester = models.IntegerField(choices=SEMESTER, default=1)
    exams = models.ManyToManyField('Exam', related_name='students', through='ExamRegister')
    is_active = models.BooleanField(default=True) # for pursose of students that left the school but can still login

    def get_contact(self):
        if self.phone:
            return self.phone
        else:
            return self.user.email  # return email if no number.

    def __str__(self):
        return str(self.user) + '  (' + str(self.user.username) + ')'

    def get_absolute_url(self):
        return reverse('headway:student_profile', kwargs={'pk': self.pk})


class Lecturer(PersonalDetails):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    qualification = models.CharField(max_length=200, help_text='Enter Highest Qualification Attained.')
    date_of_join = models.DateTimeField(auto_created=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('headway:lecturer_profile', kwargs={'pk': self.pk})


class Grade(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    graded_by = models.ForeignKey(Lecturer, on_delete=models.DO_NOTHING, null=True, blank=True)
    ca_grade = models.ForeignKey('TestGrade', blank=True, null=True, on_delete=models.SET_NULL)
    exam = models.ForeignKey('Exam', on_delete=models.CASCADE)
    marks = models.FloatField(default=0, null=True)
    grade = models.CharField(max_length=2, choices=GRADES, null=True, blank=True)  # add field to show ma A+
    date_graded = models.DateTimeField(auto_created=True, auto_now_add=True)

    def __str__(self):
        return self.student.user.get_full_name() + ' ' + str(self.grade)

    def get_absolute_url(self):
        return reverse('headway:grade_details', kwargs={'pk': self.pk})


class Exam(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField(default=True)
    courses = models.ManyToManyField(Course)
    # students = models.ManyToManyField(Student)

    def get_absolute_url(self):

headway/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.conf import settings
from .mixins import RequestKwargModelFormMixin
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from headway.models import Student, Grade,Lecturer, Course, User, Uploads


# class RequestKwargModelFormMix(object):
#    """
#    Generic model form mixin for popping request out of the Kwargs and attaching it to the instance
#    """
#    def __init__(self, *args, **kwargs):
#        self.request = kwargs.pop("request", None)  # pop the request to be passed in kwargs
#        super(RequestKwargModelFormMix, self).__init__()


class StudentSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'middle_name', 'last_name', 'username',)

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        return user


class LecturerSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_lecturer = True
        if commit:
            user.save()
        Lecturer.objects.create(user=user)
        return user


class CourseRegistrationForm(RequestKwargModelFormMixin, forms.ModelForm):

    class Meta:
        model = Student
        fields = ('courses',)

    def __init__(self, *args, **kwargs):
        super(CourseRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['courses'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['courses'].help_text = "Mark All The Courses You Will Be Taking"
        self.fields['courses'].queryset = Course.objects.filter(institution=self.request.user.institution,
                                                                program=self.request.user.student.program,
                                                                year=self.request.user.student.year,
                                                                semester=self.request.user.student.semester,)
        self.helper = FormHelper()
        self.helper.form_id = 'id_course_form'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = '#'

        self.helper.add_input(Submit('submit', 'Register'))


class LecturerCourseRegistrationForm(RequestKwargModelFormMixin, forms.ModelForm):

    class Meta:
        model = Student
        fields = ('courses',)

    def __init__(self, *args, **kwargs):
        super(LecturerCourseRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['courses'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['courses'].help_text = "Mark All The Courses You Will Be Teaching"
        self.fields['courses'].queryset = Course.objects.filter(institution=self.request.user.institution)
        self.helper = FormHelper()
        self.helper.form_id = 'id_course_form'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = '#'

        self.helper.add_input(Submit('submit', 'Register'))


class FileUploadForm(forms.ModelForm):

    class Meta:
        model = Uploads
        fields = ('name', 'file',)

    def __init__(self, *args, **kwargs):
        super(FileUploadForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id_file_upload'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = '#'

        self.helper.add_input(Submit('submit', 'Upload'))


class StudentGradeForm(forms.ModelForm):

    class Meta:
        model = Grade
        fields = ('student', 'marks',)

    def __init__(self, *args, **kwargs):
        super(StudentGradeForm, self).__init__(*args, **kwargs)

GradeStudentsFormset = forms.modelformset_factory(Grade, form=StudentGradeForm, extra=0)


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ('nrc_number','province', 'district', 'town', 'home_address', 'phone', 'birthday', 'marital_status',)

templates/headway/course_details.html
{% extends 'headway/base.html' %}
{% block title %}{{course}} Details{% endblock %}


{% block content %}
    <div class="content">
     <!-- Details For Course-->
        <div class="row">
          <div class="col-md-12">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">{{course|capfirst}} Details</h5>
                  <hr style="height: auto">
                <p class="card-category">
                   {{ course.code }} <br>
                </p>
              </div>
              <div class="card-body all-icons">

                {% include 'partials/messages.html' %}

                  <p class="text-body">{{ course.summery }}</p>
                  {% if request.user.is_lecturer %}
                      <!-- Buttons and such -->
                  <a href="{% url 'headway:grade_course' pk=course.pk %}" class="btn btn-primary">Grade Course</a>
                  {% endif %}

              </div>
            </div>
          </div>
        </div>

     <!-- Tests For Course-->
        <div class="row">
          <div class="col-md-12">
            <div class="card demo-icons">
              <div class="card-body all-icons">

            <div class="card card-plain">
              <div class="card-header">
                <h4 class="card-title"> Test Results For {{course|capfirst}} </h4>
                <p class="card-category"> List Of All Tests For This Course.</p>
              </div>
                
                      <div class="card-body">
                        {% if tests and requset.user.is_lecturer %}
                            <div class="table-responsive">
                              <table class="table">
                                <thead class=" text-primary">
                                  <th>
                                    Test Name
                                  </th>
                                  <th>
                                    Date/Time
                                  </th>
                                  <th class="text-right">
                                  </th>
                                </thead>
                                <tbody>
                                {% for test in tests %}
                                     <tr>
                                    <td>
                                      {{ test.name }}
                                    </td>
                                    <td>
                                      {{ test.date }}
                                    </td>
                                    <td class="text-right">
                                      <a href="#" class="btn btn-success btn-sm" target="_blank">Grade Test</a>
                                    </td>
                                  </tr>
                                 {% endfor %}
                                </tbody>
                              </table>
                            </div>
                        {% elif test_grades and request.user.is_student %}
                            <div class="table-responsive">
                              <table class="table">
                                <thead class=" text-primary">
                                  <th>
                                    Test Name
                                  </th>
                                  <th>
                                    Date/Time
                                  </th>
                                  <th class="text-right">
                                      Mark
                                  </th>
                                </thead>
                                <tbody>
                                {% for grade in test_grades %}
                                     <tr>
                                    <td>
                                      {{ grade.test.name }}
                                    </td>
                                    <td>
                                      {{ grade.test.date }}
                                    </td>
                                    <td class="text-right">
                                     <strong>{{ grade.mark }}%</strong>
                                    </td>
                                  </tr>
                                 {% endfor %}
                                </tbody>
                              </table>
                            </div>

                        {% else %}
                            <div class="text-center">
                                <div class="typography-line">

                                    <span class="text-danger">There Are No Test Results Here Yet...</span>
                                </div> <br>
                            </div>
                    {% endif %}
                    {% if request.user.is_lecturer %}
                  <!-- Buttons and such -->
                  <a href="#" class="btn btn-primary">Add Test</a>
              {% endif %}
                  </div>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>

    <!-- Files For Course-->
        <div class="row">
          <div class="col-md-12">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">Uploaded Files For {{course|capfirst}} </h5>
                <p class="card-category">
                   List Of All Files Uploaded For This Course. <br>
                </p>
              </div>
              <div class="card-body all-icons">
                  {% if files %}
                      <table class="table">
                            <thead class=" text-primary">
                              <th>
                                File Name
                              </th>
                              <th>
                                Upload Date/Time
                              </th>
                              <th class="text-right">
                              </th>
                            </thead>
                            <tbody>
                            {% for file in files %}
                                 <tr>
                                <td>
                                  {{ file.name }}
                                </td>
                                <td>
                                  {{ file.file }}
                                </td>

                                <td class="text-right">
                                  {% if request.user.is_lecturer %}
                                <a href="{% url 'headway:delete_file' pk=file.pk course_id=course.id  %}" class="btn btn-danger btn-sm" >
                                    <i class="nc-icon nc-simple-remove"></i>
                                    Delete
                                </a>
                                    {% endif %}
                                <a href="{{ file.file.url }}" class="btn btn-primary btn-sm" target="_blank">
                                    <i class="nc-icon nc-cloud-download-93"></i>
                                    Download
                                </a>
                                </td>
                              </tr>
                             {% endfor %}
                            </tbody>
                          </table>
                  {% else %}
                      <div class="text-center">
                      <div class="typography-line"><span class="text-danger">There Are No Files Here Yet...</span></div> <br>
                      </div>
                  {% endif %}

              {% if request.user.is_lecturer %}
                  <!-- Buttons and such -->
                  <a href="{% url 'headway:upload_file' course_id=course.id %}" class="btn btn-primary">
                      <i class="nc-icon nc-cloud-upload-94"></i>
                      Upload File
                  </a>
              {% endif %}
              </div>
            </div>
          </div>
        </div>

    <!-- Videos For Course-->
        <div class="row">
          <div class="col-md-12">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">Videos For {{course|capfirst}} </h5>
                <p class="card-category">
                   List Of All Video Series For This Course. <br>
                </p>
              </div>
              <div class="card-body all-icons">
                  {% if videos %}
                      <table class="table">
                            <thead class=" text-primary">
                              <th>
                                Series Name
                              </th>
                              <th>
                                Upload Date
                              </th>
                              <th class="text-right">
                              </th>
                            </thead>
                            <tbody>
                            {% for video in videos %}
                                 <tr>
                                <td>
                                  {{ video.name }}
                                </td>
                                <td>
                                  {{ video.date }}
                                </td>

                                <td class="text-right">
                                  {% if request.user.is_lecturer %}
                                <a href="{% url 'headway:video_delete' pk=video.pk course_id=course.id  %}" class="btn btn-danger btn-sm" >
                                    <i class="nc-icon nc-simple-remove"></i>
                                    Delete
                                </a>
                                    {% endif %}
                                <a href="{% url 'headway:video_play_list' playlist_pk=video.pk%}" class="btn btn-primary btn-sm" target="_blank">
                                    <i class="nc-icon nc-button-play"></i>
                                    Watch
                                </a>
                                </td>
                              </tr>
                             {% endfor %}
                            </tbody>
                          </table>
                  {% else %}
                      <div class="text-center">
                      <div class="typography-line"><span class="text-danger">There Are No Videos Here Yet...</span></div> <br>
                      </div>
                  {% endif %}

              {% if request.user.is_lecturer %}
                  <!-- Buttons and such -->
                  <a href="{% url 'headway:upload_video' course_id=course.pk %}" class="btn btn-primary">
                      <i class="nc-icon nc-cloud-upload-94"></i>
                      Upload Video Series
                  </a>
              {% endif %}
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

templates/headway/notifications.html
{% extends 'headway/base.html' %}
{% block title %}Notifications{% endblock %}

{% block content %}

        <!-- Allowing lectures to add notifications -->
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Notifications</h5>
                <p class="card-category">This Is Were to Find Information About Everything</p>
              </div>
              <div class="card-body ">
                  {% if request.user.is_lecturer %}
                      <a href="{% url 'headway:add_notification' %}" class="btn btn-success">
                      <i class="nc-icon nc-simple-add"></i>
                          Add Notification
                      </a>
                  {% endif %}
              </div>
            </div>
          </div>
        </div>

    {% include 'partials/messages.html' %}

    {% if news %}
        {% for notification in news %}
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">{{ notification.title }}</h5>
                <p class="card-category">{{ notification.create_date }}</p>
              </div>
              <div class="card-body ">
                <p class="notification-text" style="font-size: medium"> {{ notification.content }}</p>
              </div>
              <div class="card-footer ">
                <hr>
                <div class="stats text-success">
                  <i class="fa fa-history "></i> From: {{ notification.created_by.get_full_name }}
                    {% if notification.created_by == request.user %}
                      <a href="{% url 'headway:news_delete' pk=notification.pk %}" class="btn btn-danger btn-sm">
                               <i class="nc-icon nc-simple-remove"></i>
                               Delete
                      </a>
                  {% endif %}
                </div>

              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">No Notifications</h5>
                <p class="card-category">There Are No Notifications For You Yet</p>
              </div>
            </div>
          </div>

    {% endif %}

    {% if is_paginated %}
        <div class="pagination">
        <span class="page-link">
            {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class=" btn btn-outline-info btn-sm">
                    Previous
                <i class="nc-icon nc-minimal-left"></i>
                </a>

            {% endif %}
        <span class="page-current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
            {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class=" btn btn-outline-success btn-sm">
                    Next
                <i class="nc-icon nc-minimal-right"></i>
                </a>

            {% endif %}
        </span>
        </div>
    {% endif %}

{% endblock content %}

templates/headway/papers_confirm_delete.html
{% extends 'headway/base.html' %}
{% block title %}Delete Confirm {% endblock %}

{% block content %}
    <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Confirm Paper Deletion</h5>
              </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <p> Are you sure you want to delete "{{ object }}"?</p>
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
          </div>
{% endblock content %}